language: node_js

node_js:
  - '8'

script:
  - yarn lint
  - yarn test
  - yarn dist

deploy:
  provider: script
  script: npm run semantic-release
  skip_cleanup: true
  on:
    branch: master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
